KLASYFIKACJA (14.5)

In [1]:
import pandas as pd
penguins = pd.read_csv('penguins.csv')
penguins.dropna(inplace=True)
penguins

CulmenLength  CulmenDepth  FlipperLength  BodyMass  Species
0            39.1         18.7          181.0    3750.0        0
1            39.5         17.4          186.0    3800.0        0
2            40.3         18.0          195.0    3250.0        0
4            36.7         19.3          193.0    3450.0        0
5            39.3         20.6          190.0    3650.0        0
..            ...          ...            ...       ...      ...
339          55.8         19.8          207.0    4000.0        2
340          43.5         18.1          202.0    3400.0        2
341          49.6         18.2          193.0    3775.0        2
342          50.8         19.0          210.0    4100.0        2
343          50.2         18.7          198.0    3775.0        2

[342 rows x 5 columns]

In [2]:
features = ['CulmenLength','CulmenDepth','FlipperLength','BodyMass']
target = 'Species'

In [3]:
X, y = penguins[features], penguins[target]

In [4]:
from sklearn.decomposition import PCA
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

scaler = StandardScaler()
X_train_standardized = scaler.fit_transform(X_train)
X_test_standardized = scaler.transform(X_test)

pca = PCA(random_state=42)
X_train_pca = pca.fit_transform(X_train_standardized)
X_test_pca = pca.transform(X_test_standardized)

In [5]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, classification_report

In [6]:
#Bez PCA
decision_tree = DecisionTreeClassifier(max_depth=3, random_state=42)
decision_tree.fit(X_train_standardized, y_train)
y_pred_tree = decision_tree.predict(X_test_standardized)

print("Decision Tree:\n", classification_report(y_test, y_pred_tree))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_tree))

Decision Tree:
               precision    recall  f1-score   support

           0       0.97      1.00      0.98        30
           1       1.00      1.00      1.00        25
           2       1.00      0.93      0.96        14

    accuracy                           0.99        69
   macro avg       0.99      0.98      0.98        69
weighted avg       0.99      0.99      0.99        69

Confusion Matrix:
 [[30  0  0]
 [ 0 25  0]
 [ 1  0 13]]


In [7]:
#Z PCA
decision_tree = DecisionTreeClassifier(max_depth=3, random_state=42)
decision_tree.fit(X_train_pca, y_train)
y_pred_tree = decision_tree.predict(X_test_pca)

print("Decision Tree:\n", classification_report(y_test, y_pred_tree))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_tree))

Decision Tree:
               precision    recall  f1-score   support

           0       0.97      1.00      0.98        30
           1       1.00      1.00      1.00        25
           2       1.00      0.93      0.96        14

    accuracy                           0.99        69
   macro avg       0.99      0.98      0.98        69
weighted avg       0.99      0.99      0.99        69

Confusion Matrix:
 [[30  0  0]
 [ 0 25  0]
 [ 1  0 13]]


In [8]:
from sklearn.svm import SVC
#Bez PCA
svm = SVC(kernel='rbf', probability=True, random_state=42)
svm.fit(X_train_standardized, y_train)
y_pred_svm = svm.predict(X_test_standardized)

print("SVM:\n", classification_report(y_test, y_pred_svm))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_svm))

SVM:
               precision    recall  f1-score   support

           0       0.94      1.00      0.97        30
           1       1.00      1.00      1.00        25
           2       1.00      0.86      0.92        14

    accuracy                           0.97        69
   macro avg       0.98      0.95      0.96        69
weighted avg       0.97      0.97      0.97        69

Confusion Matrix:
 [[30  0  0]
 [ 0 25  0]
 [ 2  0 12]]


In [9]:
#Z PCA
svm = SVC(kernel='rbf', probability=True, random_state=42)
svm.fit(X_train_pca, y_train)
y_pred_svm = svm.predict(X_test_pca)

print("SVM:\n", classification_report(y_test, y_pred_svm))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_svm))

SVM:
               precision    recall  f1-score   support

           0       0.94      1.00      0.97        30
           1       1.00      1.00      1.00        25
           2       1.00      0.86      0.92        14

    accuracy                           0.97        69
   macro avg       0.98      0.95      0.96        69
weighted avg       0.97      0.97      0.97        69

Confusion Matrix:
 [[30  0  0]
 [ 0 25  0]
 [ 2  0 12]]


Wykorzystałam dwa algorytmy klasyfikacyjne - Decision Tree i SVM. Wyniki nie uległy żadnym zmianom. Warto zauważyć, że dane były już na samym początku łatwe do klasyfikacji, więc rozsądne jest założenie, że użycie tutaj PCA mogło nie przynieść wielce znaczących popraw.

REGRESJA

In [10]:
import pandas as pd
bike_data_raw = pd.read_csv('daily-bike-share.csv')
bike_data_raw

instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
0          1    1/1/2011       1   0     1        0        6           0   
1          2    1/2/2011       1   0     1        0        0           0   
2          3    1/3/2011       1   0     1        0        1           1   
3          4    1/4/2011       1   0     1        0        2           1   
4          5    1/5/2011       1   0     1        0        3           1   
..       ...         ...     ...  ..   ...      ...      ...         ...   
726      727  12/27/2012       1   1    12        0        4           1   
727      728  12/28/2012       1   1    12        0        5           1   
728      729  12/29/2012       1   1    12        0        6           0   
729      730  12/30/2012       1   1    12        0        0           0   
730      731  12/31/2012       1   1    12        0        1           1   

     weathersit      temp     atemp       hum  windspeed  rentals  
0             2  0.344167  0.363625  0.805833   0.160446      331  
1             2  0.363478  0.353739  0.696087   0.248539      131  
2             1  0.196364  0.189405  0.437273   0.248309      120  
3             1  0.200000  0.212122  0.590435   0.160296      108  
4             1  0.226957  0.229270  0.436957   0.186900       82  
..          ...       ...       ...       ...        ...      ...  
726           2  0.254167  0.226642  0.652917   0.350133      247  
727           2  0.253333  0.255046  0.590000   0.155471      644  
728           2  0.253333  0.242400  0.752917   0.124383      159  
729           1  0.255833  0.231700  0.483333   0.350754      364  
730           2  0.215833  0.223487  0.577500   0.154846      439  

[731 rows x 14 columns]

In [11]:
bike_data_raw['dteday'] = pd.to_datetime(bike_data_raw['dteday'])
bike_data = bike_data_raw.copy()
bike_data.drop(['instant', 'dteday', 'yr'], axis=1, inplace=True)

In [12]:
numeric_features = ['temp', 'atemp', 'hum', 'windspeed']
categorical_features = ['season','mnth','holiday','weekday','workingday','weathersit']
target = 'rentals'

In [13]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold
from sklearn.linear_model import ElasticNet

In [14]:
#Bez PCA
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import PowerTransformer
from sklearn.preprocessing import StandardScaler

# Podział na zmienne objaśniające i zmienną objaśnianą
X = bike_data[numeric_features+categorical_features].copy()
y = bike_data[target].copy()

# Podział na zbiór treningowy i testowy (taki sam podział co poprzednio)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)
numeric_transformer = Pipeline(steps=[
    ('logtransformer', PowerTransformer()),
    ('standardscaler', StandardScaler()),
    ('polynomialfeatures', PolynomialFeatures())])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)])

In [15]:
import numpy as np
from math import sqrt
from sklearn.metrics import mean_squared_error

In [16]:
cv = KFold(n_splits=5, shuffle=False)

In [17]:
# Tworzenie końcowego Pipeline, który będziemy trenować
final_pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                                 ('regressor', ElasticNet())])

params = {'preprocessor__num__polynomialfeatures__degree': [1, 2, 3, 4, 5],
          'regressor__alpha': [1e-3, 1e-2, 1e-1, 0.0, 1.0, 10.0, 100.0],
          'regressor__l1_ratio': np.arange(0, 1.1, 0.1)}

final_polynomial_regression_gridsearch = GridSearchCV(final_pipeline,
                                                      params,
                                                      scoring='neg_mean_squared_error',
                                                      cv=cv)

final_polynomial_regression_gridsearch.fit(X_train, y_train)
print("\nNajlepsze hiperparametry:", final_polynomial_regression_gridsearch.best_params_, "\n")

final_polynomial_regression_model = final_polynomial_regression_gridsearch.best_estimator_
predictions = final_polynomial_regression_model.predict(X_test)
print(f'RMSE: {np.sqrt(mean_squared_error(y_test, predictions))}')

C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.190e+07, tolerance: 2.207e+04 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.896e+07, tolerance: 2.268e+04 Linear regression models with null weight for the l1 regularization term are more efficiently fi


Najlepsze hiperparametry: {'preprocessor__num__polynomialfeatures__degree': 3, 'regressor__alpha': 0.1, 'regressor__l1_ratio': np.float64(0.8)} 

RMSE: 443.2085963029393


In [18]:
#Z PCA
from sklearn.decomposition import PCA

final_pipeline_with_pca = Pipeline(steps=[('preprocessor', preprocessor), ('pca', PCA(random_state=42)), ('regressor', ElasticNet())])

params_with_pca = {'preprocessor__num__polynomialfeatures__degree': [1, 2, 3, 4, 5],
                   'pca__n_components': [5, 10, 15, 20],  
                   'regressor__alpha': [1e-3, 1e-2, 1e-1, 0.0, 1.0, 10.0, 100.0],
                   'regressor__l1_ratio': np.arange(0, 1.1, 0.1)}

final_polynomial_regression_gridsearch_with_pca = GridSearchCV(final_pipeline_with_pca,
                                                               params_with_pca,
                                                               scoring='neg_mean_squared_error',
                                                               cv=cv)

final_polynomial_regression_gridsearch_with_pca.fit(X_train, y_train)
print("\nNajlepsze hiperparametry:", final_polynomial_regression_gridsearch_with_pca.best_params_, "\n")

final_polynomial_regression_model_with_pca = final_polynomial_regression_gridsearch_with_pca.best_estimator_
predictions_pca = final_polynomial_regression_model_with_pca.predict(X_test)
print(f'RMSE: {np.sqrt(mean_squared_error(y_test, predictions_pca))}')

C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.713e+07, tolerance: 2.207e+04 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.322e+07, tolerance: 2.268e+04 Linear regression models with null weight for the l1 regularization term are more efficiently fi


Najlepsze hiperparametry: {'pca__n_components': 10, 'preprocessor__num__polynomialfeatures__degree': 1, 'regressor__alpha': 1.0, 'regressor__l1_ratio': np.float64(1.0)} 

RMSE: 503.72447840843535


(Wartość RMSE dla modelu bez PCA różni się nieco od wartości w poprzednim zadaniu, gdyż tam modyfikowaliśmy nieco cechy). Tutaj dochodzimy do zaskakujących konkluzji - test RMSE wyszedł gorzej dla modelu, który używał PCA! Ponadto, GridSearch wybrał dla opcji z PCA odmienne hiperparametry. Możliwe, że PCA usuwa niektóre cechy, które wydają się mniej znaczące, lecz mają wysokie powiązanie z targetem, lub że dochodzi do oversimplification i do utraty informacji.